main = ".open-next/worker.js"
name = "portfolio-website"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]
[assets]
directory = ".open-next/assets"
binding = "ASSETS"
routes = [
  { pattern = "alexmonk.au", custom_domain = true }
]